/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BigImage: typeof import('./src/components/home/bigImage.vue')['default']
    BridButton: typeof import('./src/components/bridButton.vue')['default']
    DesktopPet: typeof import('./src/components/desktopPet/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/home/header.vue')['default']
    InfoCard: typeof import('./src/components/about/info-card.vue')['default']
    Intro: typeof import('./src/components/about/intro.vue')['default']
    IntroCard: typeof import('./src/components/about/intro-card.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    MediaCard: typeof import('./src/components/mediaCard.vue')['default']
    PetContextMenu: typeof import('./src/components/desktopPet/petContextMenu.vue')['default']
    Psw: typeof import('./src/components/psw.vue')['default']
    QuickAccessCard: typeof import('./src/components/quickAccessCard.vue')['default']
    QuickAccessCardNew: typeof import('./src/components/quickAccessCardNew.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scale: typeof import('./src/components/scale.vue')['default']
    SkillCard: typeof import('./src/components/about/skill-card.vue')['default']
    SuspendedMenu: typeof import('./src/components/suspended-menu/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TerminalWindow: typeof import('./src/components/terminal-window/index.vue')['default']
    Wave: typeof import('./src/components/home/wave.vue')['default']
    WeatherRadio: typeof import('./src/components/weatherRadio.vue')['default']
    WindowsTerminal: typeof import('./src/components/windows-terminal.vue')['default']
    ZModal: typeof import('./src/components/zModal.vue')['default']
  }
}
